### ISSUE TITLE
issue in docker

### ISSUE THREAD

**Issue by RamadanAhmed** [mpkuse/cerebro#10]
Hi,
I ran from docker and every time it display this message and after 71 sec it fails 
[Cerebro::wait_until__connectedToDescServer_and_descSizeAvailable] waiting for `descriptor_size_available` to be true. timeout_in_sec=71
if you could help me, I'll be glad

**Comment by mpkuse** [comment]
Seem like the whole image description server is not running. Make sure it is running. Look at the launch file there should be a group for it. Make sure it is enabled.
