### ISSUE TITLE
map reuse?

### ISSUE THREAD

**Issue by MoonUniverse** [mpkuse/cerebro#7]
It is really exciting to see this code released! Amazing!

Dose this code support the map reuse? map save? map load? relocalization?

Kind Regards!

**Comment by mpkuse** [comment]
Hi, I am glad you are interested in this. Yes there is support for map reuse. Checkout the dev-save .... Branch. I have tested the code for correctness. Doing more test after which I plan to merge into master. Feel free to checkout that branch and give it a try
